## A typical Makefile for compiling latex sources using a blang/latex docker container

ifndef PDFVIEWER
	PDFVIEWER=mupdf
endif

CONTAINER=latexdockercmd.sh /bin/sh -c
PDFLATEX_BIN=pdflatex
PDFLATEX_OPTS=-shell-escape -halt-on-error
MAKEGLOSSARIES_BIN=makeglossaries
BIBTEX_BIN=bibtex

.PHONY: all debug debugcmd clean clean-src clean-pdf show

default: p.pdf clean-src

all: p.pdf clean-src

p.pdf: p.tex glossar.tex directory.bib
	$(CONTAINER) "$(PDFLATEX_BIN) $(PDFLATEX_OPTS) p.tex && $(MAKEGLOSSARIES_BIN) p && $(BIBTEX_BIN) p && \
		$(PDFLATEX_BIN) $(PDFLATEX_OPTS) p.tex && $(MAKEGLOSSARIES_BIN) p && $(PDFLATEX_BIN) $(PDFLATEX_OPTS) p.tex"

debug: debugcmd clean-src

debugcmd: p.tex glossar.tex directory.bib
	$(CONTAINER) "$(PDFLATEX_BIN) $(PDFLATEX_OPTS) p.tex && $(MAKEGLOSSARIES_BIN) p && $(BIBTEX_BIN) p"

clean: clean-src clean-pdf

clean-src:
	rm -f p.aux p.log p.out p.toc p.glg p.glo p.gls p.ist p.lof \
		p.nav p.out p.snm p.toc p.vrb p.acn p.acr p.alg p.bbl p.blg p-blx.bib p.dvi p.lol p.pyg p.run.xml p.glsdefs

clean-pdf:
	rm -f p.pdf p.pdf

show: p.pdf clean-src
	$(PDFVIEWER) p.pdf
